language: scala

scala:
   - 2.12.10

script:
  - cd pgb &&  
    sbt ++$TRAVIS_SCALA_VERSION clean coverage test && 
    sbt ++$TRAVIS_SCALA_VERSION coverageReport && 
    sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - sbt publishLocal
  - cd ../pgb-it && 
    sbt ++$TRAVIS_SCALA_VERSION reload plugins &&
    sbt ++$TRAVIS_SCALA_VERSION clean test

sudo: false
