language: scala

scala:
   - 2.12.4

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

sudo: false
